export const defaultProperties = {
  noiseStrength: 0.1,
  // for gradient-scene
  type: "plane",
  animate: "off",
  movements: 0.2,
  speed: 1.8,
  bumpScale: 1.3,
  rotationX: 180,
  rotationY: 0,
  rotationZ: 0,
  env: "env",
  postProcessing: "threejs",
  cameraPositionX: 0,
  cameraPositionY: 3.2,
  cameraPositionZ: 0,
  cameraQuaternionX: -1.6,
  cameraQuaternionY: 0,
  cameraQuaternionZ: 0,
  cameraZoom: 0.5,
}
